export type Category = "Water Tanks" | "Rain Pipes" | "Drip Lines" | "Solar" | "Pipes & Fittings";

export interface Product {
  id: string;
  name: string;
  price: string;
  short: string;
  description: string;
  specs: string[];
  variants: string[];
  category: Category;
  emoji: string;
  image: string;
}

export const CATEGORIES: ("All" | Category)[] = [
  "All",
  "Water Tanks",
  "Rain Pipes",
  "Drip Lines",
  "Solar",
  "Pipes & Fittings",
];

export const PRODUCTS: Product[] = [
  {
    id: "tank-5000",
    name: "5000L Alfa Water Tank",
    price: "$360",
    short: "Heavy-duty polyethylene tank, UV resistant",
    description:
      "Built for the long haul — our 5000L Alfa tank is the workhorse of commercial farms. UV-stabilised polyethylene means it shrugs off the Zimbabwean sun, year after year.",
    specs: ["Capacity: 5000 litres", "Material: UV-stabilised polyethylene", "Food-grade safe", "10-year warranty"],
    variants: ["Black", "Green"],
    category: "Water Tanks",
    emoji: "🛢️",
    image: "https://images.unsplash.com/photo-1773414582372-43ed2b1db2e2?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "tank-2500",
    name: "2500L Alfa Water Tank",
    price: "$220",
    short: "Mid-size farm storage tank",
    description: "The sweet spot for mid-size operations. Reliable storage with the same UV-resistant build as our larger tanks.",
    specs: ["Capacity: 2500 litres", "UV-stabilised", "Threaded outlets"],
    variants: ["Black", "Green"],
    category: "Water Tanks",
    emoji: "🛢️",
    image: "https://images.unsplash.com/photo-1773171033770-005fb44f42ca?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "tank-1000",
    name: "1000L Alfa Water Tank",
    price: "$115",
    short: "Compact tank ideal for small-scale use",
    description: "Perfect for small plots, household use, or as a buffer tank. Compact yet rugged.",
    specs: ["Capacity: 1000 litres", "UV-stabilised", "Easy to relocate"],
    variants: ["Black", "Green"],
    category: "Water Tanks",
    emoji: "🛢️",
    image: "https://images.unsplash.com/photo-1773414582372-43ed2b1db2e2?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "rain-28",
    name: "28mm x 200m Rain Pipe",
    price: "$28",
    short: "Even, gentle crop coverage",
    description: "Designed for delicate crops. Gentle, even water distribution over long runs.",
    specs: ["Diameter: 28mm", "Length: 200m", "Low pressure"],
    variants: ["200m roll"],
    category: "Rain Pipes",
    emoji: "💧",
    image: "https://images.unsplash.com/photo-1743742566156-f1745850281a?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "rain-32",
    name: "32mm x 200m Rain Pipe",
    price: "$32",
    short: "Medium pressure coverage",
    description: "Step up in flow rate for medium-pressure systems. Great all-rounder.",
    specs: ["Diameter: 32mm", "Length: 200m", "Medium pressure"],
    variants: ["200m roll"],
    category: "Rain Pipes",
    emoji: "💧",
    image: "https://images.unsplash.com/photo-1738598665698-7fd7af4b5e0c?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "rain-40",
    name: "40mm x 200m Rain Pipe",
    price: "$40",
    short: "High-volume coverage",
    description: "High-volume option for larger fields and demanding crop schedules.",
    specs: ["Diameter: 40mm", "Length: 200m", "High flow"],
    variants: ["200m roll"],
    category: "Rain Pipes",
    emoji: "💧",
    image: "https://images.unsplash.com/photo-1743742566156-f1745850281a?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "rain-50",
    name: "50mm x 100m Rain Pipe",
    price: "$45",
    short: "Heavy-duty short run pipe",
    description: "Heavy-duty 50mm pipe for short, high-volume runs and mainline applications.",
    specs: ["Diameter: 50mm", "Length: 100m", "Heavy duty"],
    variants: ["100m roll"],
    category: "Rain Pipes",
    emoji: "💧",
    image: "https://images.unsplash.com/photo-1738598665698-7fd7af4b5e0c?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "drip-2000",
    name: "2000m Dripline (0.2mm)",
    price: "$100",
    short: "Ideal for horticulture and high-value crops",
    description: "Precision drip irrigation for horticulture. Maximises water efficiency for high-value crops.",
    specs: ["Length: 2000m", "Wall: 0.2mm", "Emitter spacing: 30cm"],
    variants: ["2000m roll"],
    category: "Drip Lines",
    emoji: "🌱",
    image: "https://images.unsplash.com/photo-1738598665806-7ecc32c3594c?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "drip-1500",
    name: "1500m Dripline (0.3mm)",
    price: "$110",
    short: "Thicker wall, longer lasting",
    description: "Thicker-walled dripline built to last multiple seasons under tough field conditions.",
    specs: ["Length: 1500m", "Wall: 0.3mm", "Multi-season"],
    variants: ["1500m roll"],
    category: "Drip Lines",
    emoji: "🌱",
    image: "https://images.unsplash.com/photo-1738598665806-7ecc32c3594c?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "solar-panel",
    name: "Solar Panel (250W)",
    price: "Contact for pricing",
    short: "Monocrystalline, farm-grade",
    description: "Farm-grade 250W monocrystalline solar panel. Tested for the African sun and built to last.",
    specs: ["250W", "Monocrystalline", "25-year output warranty"],
    variants: ["Single panel", "Pack of 4", "Pack of 8"],
    category: "Solar",
    emoji: "☀️",
    image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "solar-inverter",
    name: "Solar Inverter",
    price: "Contact for pricing",
    short: "Suitable for pump and farm use",
    description: "Robust inverter sized for farm pumps and small-to-medium installations. Multiple wattages available.",
    specs: ["Pure sine wave", "MPPT", "Farm-rated"],
    variants: ["3kW", "5kW", "10kW"],
    category: "Solar",
    emoji: "⚡",
    image: "https://images.unsplash.com/photo-1680355065203-43ad84bb6e69?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "solar-package",
    name: "Full Solar Installation Package",
    price: "Contact for pricing",
    short: "Panels, inverter, wiring, installation",
    description: "Turnkey solar installation: panels, inverter, batteries (optional), wiring, mounting and professional install — all in one package.",
    specs: ["Site survey included", "Professional installation", "After-sales support"],
    variants: ["Small farm", "Medium farm", "Commercial"],
    category: "Solar",
    emoji: "🔆",
    image: "https://images.unsplash.com/photo-1629726797843-618688139f5a?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "hdpe",
    name: "HDPE Pipes (various sizes)",
    price: "Contact for pricing",
    short: "High-density polyethylene, pressure-rated",
    description: "Pressure-rated HDPE pipes for mainlines, boreholes and reticulation. Multiple diameters in stock.",
    specs: ["PE100 grade", "Pressure rated", "20mm – 110mm"],
    variants: ["20mm", "32mm", "50mm", "75mm", "110mm"],
    category: "Pipes & Fittings",
    emoji: "🔧",
    image: "https://images.unsplash.com/photo-1766651897083-62a5379b3d7d?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "pump",
    name: "Submersible Water Pump",
    price: "Contact for pricing",
    short: "For borehole and tank systems",
    description: "Reliable submersible pumps for boreholes and tanks. Solar-compatible options available.",
    specs: ["Various head & flow ratings", "Solar-compatible options", "Stainless steel"],
    variants: ["0.75HP", "1HP", "1.5HP", "2HP"],
    category: "Pipes & Fittings",
    emoji: "🚰",
    image: "https://images.unsplash.com/photo-1534641614095-6222aed9bdd6?auto=format&fit=crop&w=600&h=450&q=80",
  },
  {
    id: "fittings",
    name: "Pipe Fittings & Connectors",
    price: "Contact for pricing",
    short: "Full range of joints, elbows, tees",
    description: "Complete range of fittings — elbows, tees, reducers, valves, connectors. Everything to finish the job.",
    specs: ["Compression & threaded", "All standard sizes", "Bulk pricing available"],
    variants: ["Mixed pack", "Bulk order"],
    category: "Pipes & Fittings",
    emoji: "🔩",
    image: "https://images.unsplash.com/photo-1759950345204-dae34876d9cb?auto=format&fit=crop&w=600&h=450&q=80",
  },
];

export const WHATSAPP = "https://wa.me/263776611049";
export const orderLink = (productName: string) =>
  `${WHATSAPP}?text=${encodeURIComponent(`Hi IrriTech, I'd like to order: ${productName}`)}`;
